### ISSUE TITLE
Call piera from himl.

### ISSUE THREAD

**Issue by frimik** [adobe/himl#12]
Currently looking at how to integrate himl with piera (which I'm using extensively).

Hopefully I can sort it and can come back with the results.

https://github.com/b1naryth1ef/piera

**Comment by dancb10** [comment]
@frimik I know that we've looked at piera when we started with himl and it missed some functionalities that we needed. Things like deep merging, secret or dict interpolations if I remember correctly were missing. There is no compatibility between these two.

**Comment by danielcoman** [comment]
Won't implement.
