### ISSUE TITLE
Build a docker image as part of release process

### ISSUE THREAD

**Issue by amuraru** [adobe/himl#26]

**Comment by danielcoman** [comment]
Himl can be easily installed in any tooling container. I don't see the value of maintaining a docker image only for this as it's usually part of a bigger toolset.
How a tooling/tools container should look is a highly opinionated thing and varies with workflows.
I think we should keep the scope focused on what himl does and not go into the business of maintaining a base image.

**Comment by danielcoman** [comment]
I'll mark this as `wontfix` and keep this issue opened a while longer, if there are any other opinions on this.
