### ISSUE TITLE
himl cli --filter deep keys

### ISSUE THREAD

**Issue by tiger-revaapriyan** [adobe/himl#40]
On the stated `example/simple/default.yaml` trying to access `key1` in `deep.key1` results in empty dict.

`examples/simple/default.yaml`

```env: default
deep:
  key1: v1
  key2: v2
deep_list:
- item1
- item2
```
Commands tried from `himl` directory

```
himl --filter deep.key1 examples/simple
himl --filter deep[key1] examples/simple
himl --filter deep{key1} examples/simple
```

### Expected Behaviour
`key1: v1`

### Actual Behaviour
`{}`

#### Platform and Version
Platform: Ubuntu 20.04 LTS
```himl --version
himl v0.7.1
```

**Comment by danielcoman** [comment]
@tiger-revaapriyan Filtering is only supported for top keys: `himl --filter deep examples/simple `
```
deep:
  key1: v1
  key2: v2
```

**Comment by tiger-revaapriyan** [comment]
@danielcoman Thanks. I was hoping to filter deep. Hoping for the same in the future as `enhancement`

**Comment by danielcoman** [comment]
@tiger-revaapriyan Can you please open up a feature requests? If there is a need for this we'll look into it.

**Comment by tiger-revaapriyan** [comment]
Opened #42 as Feature Request.
