### ISSUE TITLE
Reading config from S3 bucket

### ISSUE THREAD

**Issue by Revaapriyan** [adobe/himl#43]
It would be helpful if an efficient way to read the config (or process it) from S3 storage.  `boto3` client get the file ('s3://path/to/.yaml') as BytesIO which will not be merged with any `default.yaml` in the `config` folder.

**Comment by Revaapriyan** [comment]
@danielcoman It would be great if reading from s3 is feasible.

**Comment by danielcoman** [comment]
@Revaapriyan, himl supports key value [interpolation](https://github.com/adobe/himl#secrets-retrieval) (retrieval) from S3 and SSM.
Main use case behind himl is to merge the files in a given hierarchy, you can generate the output in a desired path where you store some configs that you do not want merged.

**Comment by danielcoman** [comment]
@Revaapriyan please reopen if needed
