### ISSUE TITLE
Use setuptools extras for extra dependencies

### ISSUE THREAD

**Issue by aslafy-z** [adobe/himl#44]
These integrations https://github.com/adobe/himl#feature-secrets-retrieval depends on external packages which are not required for the basic operation of the package.

What do you think of moving these dependencies (boto, hvac...) to extra_requires ?
https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#id7

Then users will be able to install the simple package with `pip install himl` and add functionnality with `pip install himl[vault, aws]`

**Comment by costimuraru** [comment]
That's actually a nice idea. I think we can do something like that.
